config/routes.rb
Rails.application.routes.draw do
  resources :plants

  root :to => 'plants#index'
  post '/plants/search' => 'plants#search', as: 'plants_search'

end

app/models/plant.rb
class Plant < ActiveRecord::Base

	def self.search search
		if search
    	where('common_name LIKE ?', "%#{search}%")
  	else
	    all
  	end
  end
end

# http://railscasts.com/episodes/240-search-sort-paginate-with-ajax?autoplay=true
# http://railscasts.com/episodes/228-sortable-table-columns?autoplay=true

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  helper_method :sort_column, :sort_direction

  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  # GET /plants
  # GET /plants.json
  def index
    #sort_column y sort_direction están en métodos privados, ABAJO
    @plants = Plant.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 4, :page => params[:page])
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @plants = Plant.search params[:search]
    render 'index'
  end

  private
    def sort_column
      Plant.column_names.include?(params[:sort]) ? params[:sort] : "common_name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"      
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
      params.require(:plant).permit(:common_name, :scientific_name, :max_temp, :min_temp, :description, :url_image, :url_flower_image, :url_leaves_image, :watering)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable column, title = nil
		title ||= column.titleize
		css_class = column == sort_column ? "current #{sort_direction}" : nil
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	end
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExampleApp</title>
  <link rel="stylesheet" href="http://s3.amazonaws.com/codecademy-content/courses/ltp/css/bootstrap.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/plants/_form.html.erb
<%= form_for(@plant) do |f| %>
  <% if @plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% @plant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :common_name %><br>
    <%= f.text_field :common_name %>
  </div>
  <div class="field">
    <%= f.label :scientific_name %><br>
    <%= f.text_field :scientific_name %>
  </div>
  <div class="field">
    <%= f.label :min_temp %><br>
    <%= f.number_field :min_temp %> ºC
  </div>
  <div class="field">
    <%= f.label :max_temp %><br>
    <%= f.number_field :max_temp %> ºC
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :url_image %><br>
    <%= f.text_field :url_image %>
  </div>
  <div class="field">
    <%= f.label :url_flower_image %><br>
    <%= f.text_field :url_flower_image %>
  </div>
  <div class="field">
    <%= f.label :url_leaves_image %><br>
    <%= f.text_field :url_leaves_image %>
  </div>
  <div class="field">
    <%= f.label :watering %><br>
    <%= f.text_field :watering %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plants/_plants_table.html.erb
<table class="pretty">
    <thead>
      <tr>
        <th><%= sortable "common_name", "Nombre común" %></th>
        <th><%= sortable "scientific_name", "Nombre científico" %></th>
        <th><%= sortable "min_temp", "Temperatura mínima" %></th>
        <th><%= sortable "max_temp", "Temperatura máxima" %></th>
        <th>Imagen</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @plants.each do |plant| %>
        <tr>
          <td><%= plant.common_name %></td>
          <td id="scientific_name"><%= plant.scientific_name %></td>
          <td><%= plant.min_temp %> ºC</td>
          <td><%= plant.max_temp %> ºC</td>
          <td class="thumbnail images_in_index"><img src="<%= plant.url_image %>"></td>
          <td><%= link_to 'Mostrar', plant %></td>
          <td><%= link_to 'Editar', edit_plant_path(plant) %></td>
          <td><%= link_to 'Borrar', plant, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= will_paginate @plants %>

app/views/plants/edit.html.erb
<h1>Editing Plant</h1>

<%= render 'form' %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>Listing Plants</h1>
    </div>
    <div class="col-md-6">
      <p class='searching'>
        <%= form_tag plants_search_path, :method => 'get', :id => "plants_search" do %>
        <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Buscar", :name => nil %>
        </p>
      <% end %>
      </p>
    </div>
  </div>
</div>

<div class="container">
  <span id="plants_table"><%= render :partial => "plants_table" %></span>
</div>

<br>

<div class="container">
  <%= link_to 'Nueva planta', new_plant_path %> | 
  <%= link_to 'Regresar al listado de plantas', plants_path %>
</div>

app/views/plants/index.js.erb
$("#plants_table").html("<%= escape_javascript(render("plants_table")) %>")

app/views/plants/new.html.erb
<h1>New Plant</h1>

<%= render 'form' %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @plant.common_name %>, <span id="scientific_name"><%= @plant.scientific_name %></span>
</p>

<p>
  <strong>Temperatura mínima:</strong>
  <%= @plant.min_temp %> ºC
</p>

<p>
  <strong>Temperatura máxima:</strong>
  <%= @plant.max_temp %> ºC
</p>

<% if @plant.description.present? %>
<p>
  <strong>Descripción:</strong>
  <%= @plant.description %>
</p>
<% end %>

<p>
  <img src="<%= @plant.url_image %>">
</p>

<% if @plant.url_flower_image.present? %>
  <p>
    <strong>Flores:</strong>
    <img src="<%= @plant.url_flower_image %>">
  </p>
<% end %>

<% if @plant.url_leaves_image.present? %>
  <p>
    <strong>Hojas:</strong>
    <img src="<%= @plant.url_leaves_image %>">
  </p>
<% end %>

<h3>Cuidados:</h3>

<p>
  <strong>Riego:</strong>
  <%= @plant.watering %>
</p>


<%= link_to 'Editar', edit_plant_path(@plant) %> |
<%= link_to 'Regresar al listado de plantas', plants_path %>